export const SAVE_LOGIN_USERINFO = 'SAVE_LOGIN_USERINFO';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const SAVE_CUSTOMER_INFO = 'SAVE_CUSTOMER_INFO';
export const IS_LOADING = 'IS_LOADING';